### PR TITLE
BOM-1682: Fix python 3.8 test failures

### PR DESCRIPTION
**Pull request by iamsobanjaved**
**JIRA:** [BOM-1682](https://openedx.atlassian.net/browse/BOM-1682)

### CODE REVIEW

**Comment by iamsobanjaved** [comment]
@morenol please review

**Comment by iamsobanjaved** [comment]
@jmbowman kindly review this

**Comment by awais786** [comment]
@morenol please review.

**Comment by awais786** [comment]
> @morenol please review.

Oh you already approved.

**Pull request merged**
