### PR TITLE
Remove django-sphinx-autodoc package

### PR DESCRIPTION
**Pull request by NeOneSoft**
This PR was created to remove django-sphinx-autodoc in order to close https://github.com/edx/upgrades/issues/66 Django 3.2 issue

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @NeOneSoft! I've created [OSPR-6063](https://openedx.atlassian.net/browse/OSPR-6063) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by awais786 — APPROVED** [review]

**Comment by edx-webhook** [comment]
@NeOneSoft 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ease&entry.867055334=https://github.com/edx/ease/pull/95&entry.1484655318=https://github.com/NeOneSoft&entry.752974735=2021-09-21+20:52&entry.1917517419=2021-09-22+05:16&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@NeOneSoft Thanks for your contribution!

**Comment by NeOneSoft** [comment]
Thank you for ytour support @natabene !!

**Pull request merged**
